I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 387, in script
    scene black with flash
  File "game/script.rpy", line 387, in <module>
    scene black with flash
NameError: name 'flash' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 387, in script
    scene black with flash
  File "c:\Users\owner's\Downloads\renpy-8.3.7-sdk.7z\renpy-8.3.7-sdk\renpy\ast.py", line 1367, in execute
    trans = renpy.python.py_eval(self.expr)
  File "c:\Users\owner's\Downloads\renpy-8.3.7-sdk.7z\renpy-8.3.7-sdk\renpy\python.py", line 1218, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "c:\Users\owner's\Downloads\renpy-8.3.7-sdk.7z\renpy-8.3.7-sdk\renpy\python.py", line 1211, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/script.rpy", line 387, in <module>
    scene black with flash
NameError: name 'flash' is not defined

Windows-10-10.0.19045 AMD64
Ren'Py 8.3.7.25031702
The Last Message 1.0
Sat Jul 12 09:49:00 2025
